### ISSUE TITLE
Preprocessor Lexer

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/Gladell#1]
The preprocessor lexer will be responsible for organizing all preprocessing constructs into something consumable by the core HLSL -> (Whatever) compiler, and thus must spit out, ideally, some kind of basic IR that has all the constructs that the core HLSL compiler will expect.

Note that the HLSL compiler is seperate from the HLSL lexer/parser. The latter consumes an already preprocessed source in some unspecified implementation-defined format, while the former takes regular source and then runs it through the preprocessor lexer / parser / analyzer and then hands THAT off to actual language lexer/parser/analyzer.

**Comment by ThePhD** [comment]
Lexer completed in 17ed4978310311b2f0eff912944057653be50a97.

**Comment by ThePhD** [comment]
@Borgleader - https://gist.github.com/ThePhD/5b8048363dd99d11f001
It's just tokens for now, but it's proof that it's working. Generated from @Rapptz's jsonpp

**Comment by Borgleader** [comment]
Looks good, a few notes though (not sure if it's the right place for it, but I couldn't find anywhere else):
- Minor tidbit, in `main`, not sure if you did that on purpose or not but it's the only place where you don't use `gld::string_view` and instead you redo the `using` statement that is in `string.hpp` which I found odd.
- In `inline string_view to_string( token_id id )`, it looks like all the ids are sequential, so it would be faster to just index into an array. Cuts the code in half too.

Congratz on being 5 days early ;)
