### ISSUE TITLE
Confirmed Gladell runs without full Furrovine

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/Gladell#4]
The dependencies of Furrovine were split into Furrovine.Heart and Furrovine.Unicode. Need to confirm it can be built and run without the whole Furrovine, making it a self-contained public repo.

**Comment by ThePhD** [comment]
@Borgleader When you have some time, would you mind pulling Gladell, opening the Project (Visual Studio 2015 RC), and see if anything explodes? I need to make sure this is as self-contained as humanly possible.

**Comment by Borgleader** [comment]
@ThePhD Sure, but I'll need to install VS2015 first, I was kinda waiting on the full release before getting it.

**Comment by ThePhD** [comment]
If you don't have VS 2015, it's alright! It's really heavy to install the RC (though it doesn't seem to break old VSs), so if you don't already have it don't worry about it!

**Comment by Borgleader** [comment]
Ok so I installed VS2015 on my old desktop. I got a bunch of unresolved external symbols (by a bunch I mean 8). I looked into it and your solution configuration is messed up. The unicode lib's platform is set to X64, the other two are set to X86. I switched back Furrovine++.Unicode's Platform back to Win32 and now it's all good.

You're also missing a post build step to copy the dll from the that project's output folder to Gladell's output folder.

I didn't run it with any command line arguments or files. Not sure if there's any test data to use it with? 

P.S: Nice work on the git submodules thing, everything got checked out in one go.

**Comment by ThePhD** [comment]
I'm glad the submoduling works... that took a lot of thinking and re-organizing to get good.

I'm hoping to either put the Post Build Step inside of Gladell OR figuring out if there's a natural inborn mechanic that copies final outputs to the target directory inside of Visual Studio without having to make some ridiculous robocopy dependency. I thought that having it explicitly "as a reference" would do the trick, but... alas.

**Comment by ThePhD** [comment]
Some more checking yields that it is indeed set as a reference project in VS 2015 RC and that it should be copying the DLL to the final output directory without any direct intervention from you @Borgleader ... I'm perplexed as to why it's not doing that.

Make sure the Solution Explorer has "Show All Files" set to off so you can see the "References" pseudo-folder. Pop it open, right-click on the "Furrovine++.Unicode" reference, and make sure it has "Copy Local" set to True... which it should (I double-checked under latest commit).

**Comment by Borgleader** [comment]
@ThePhD I checked, and as you say it is there in the Reference folder and "Copy Local" is set to true, but when I press F5 I get a popup saying "... can't start because Furrovine++.Unicode.dll is missing."

I tried the "Set local copy to false then true" solution from [this SO question](http://stackoverflow.com/questions/1132243/msbuild-doesnt-copy-references-dlls-if-using-project-dependencies-in-solution) but no luck.

**Comment by ThePhD** [comment]
How... shitty of Visual Studio. I guess I'll have to add a post-build script into Gladell or something. Thanks for testing this for me.

**Comment by ThePhD** [comment]
Should be all fixed in https://github.com/ThePhD/Gladell/commit/7c386c3e2dbef38004dbe231e363df8d205fb19f @Borgleader. It comes at the cost of manually dictating the output directories since I didn't want to force a build script, but on the bright side this is actually a much nicer project directory structure (and also the property sheet has the benefit of preventing object file name collisions if there's 2 .cxx files with the same name but in different directories).

**Comment by Borgleader** [comment]
@ThePhD Did you forget to submit Gladell.sln? I reverted all my local changes, pulled all the stuff and I got the same link errors as earlier. I had to redo this modification:

```
- 48 {428452AC-A577-436E-9E32-2460653AD0E6}.Debug|x64.ActiveCfg = Debug|x64
+ 48 {428452AC-A577-436E-9E32-2460653AD0E6}.Debug|x64.ActiveCfg = Release|Win32

- 87 {D4D6B539-DC7E-444A-9381-1EF652FE5C38}.Debug|x64.ActiveCfg = Debug|x64
+ 87{D4D6B539-DC7E-444A-9381-1EF652FE5C38}.Debug|x64.ActiveCfg = Release|Win32
```

With that, I was able to compile and run (after cleaning the solution), and I didn't have to manually copy the .dll.

**Comment by ThePhD** [comment]
Sorry about that, the cleaning I did didn't get submitted. It should be on the latest branch now. Guess I'm still bad at version control.

**Comment by Borgleader** [comment]
Yep it's all good, cleaned out the solution, pressed F5, everything got built and it ran without complaining about a missing dll. I guess you can close the issue now.

**Comment by ThePhD** [comment]
Can do! Thanks for testing it out for me. :heart_decoration:
